name: Trigger sync

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'openops-cloud/openops'
    steps:
      - name: Get token from Github App
        id: app_token
        uses: actions/create-github-app-token@v2.2.1
        with:
          app-id: ${{ vars.DEVOPS_GITHUB_APP_ID }}
          private-key: ${{ secrets.DEVOPS_GITHUB_APP_PEM }}
          owner: ${{ github.repository_owner }}
      - name: Trigger sync
        env:
          GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}
        run: |
          gh workflow run sync.yml -f ref=${{ github.sha }} -R openops-cloud/openops-internal
